# Generated by Django 2.1.5 on 2019-01-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='streetnumber',
            field=models.CharField(max_length=255, verbose_name='numéro'),
        ),
    ]
