# Generated by Django 2.1.5 on 2019-01-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20190105_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='téléphone'),
        ),
    ]
